# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e524cdd362c63a940848675694c650cf28525dd552824261d9de8a9cff5cdf2e5c778b9224df9598eb286036d50ac6bb77471ca35065b9d81e8729b006c7f4a4

test:
  secret_key_base: e000c840ea0e5afb86c7b1d0cf11b4ee8aa958e559566c122d3b12307678232077ce98e508b153dbbd62c84091e23b596f00915c42b79d9894f45c26d96b0849

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
